  - name: Update apt package index and install packages for HTTPS repositories
    shell: |
      sudo apt-get update
      sudo apt-get install -y ca-certificates curl gnupg

  - name: Add Docker GPG key
    shell: |  
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg

  - name: Add Docker repository to apt sources
    shell: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Install Docker Engine
    shell: |
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
