version: '3'
services:
    backend:
        build: .
        image: backend
        container_name: backend
        ports:
            - 8080:8080
        environment:
            COUCHDB_USERNAME: admin
            COUCHDB_PASSWORD: password
            COURCHDB_PORT: 5984
            COUCHDB_HOSTS: 172.26.136.11,172.26.129.176,172.26.129.51
