- name: Install docker-compose python package
  pip:
    name: docker-compose

- name: Take down existing crawler container
  command:
    cmd: "docker-compose -f /home/ubuntu/COMP90024/harvest/docker-compose-{{ inventory_hostname }}.yml down --rmi local"
  ignore_errors: true

- name: Generate Docker Compose files for each crawler
  template:
    src: roles/deploy_crawler/templates/docker-compose.j2
    dest: "/home/ubuntu/COMP90024/harvest/docker-compose-{{ inventory_hostname }}.yml"

- name: Run Docker Compose
  command:
    cmd: "docker-compose -f /home/ubuntu/COMP90024/harvest/docker-compose-{{ inventory_hostname }}.yml up -d"

- name: Disable crawler container
  command:
    cmd: "docker-compose -f /home/ubuntu/COMP90024/harvest/docker-compose-{{ item }}.yml down --rmi local"
  ignore_errors: true
  loop: "{{ groups['DISABLE_CRAWLERS'] }}"