# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: group9_key
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom-internal

# location to save the IP addresses
ip_file: "./inventory/instance_addresses.ini"

# Volume
volumes:
  - vol_name: instance0-volume
    vol_size: 150
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance1-volume
    vol_size: 150
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance2-volume
    vol_size: 150
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance3-volume
    vol_size: 50
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024


# Security group
security_groups:
  - name: all_ports
    description: "Demo security group for all ports"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: udp_port_4789
    description: "Demo security group for udp port_4789"
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_ip_prefix: 0.0.0.0/0
  - name: udp_port_7946
    description: "Demo security group for udp port_7946"
    protocol: udp
    port_range_min: 7946
    port_range_max: 7946
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance0
    volume_ids: '{ instance0_volumes|default([]) }'
    volumes: ['instance0-volume']
  - name: instance1
    volume_ids: '{ instance1_volumes|default([]) }'
    volumes: ['instance1-volume']
  - name: instance2
    volume_ids: '{ instance2_volumes|default([]) }'
    volumes: ['instance2-volume']
  # - name: instance3
  #   security_groups: instance3-security-group
  #   volume_ids: '{ instance3_volumes|default([]) }'
  #   volumes: ['instance3-volume']
 