version: '3'
services:
  frontendapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontendapp:latest
    environment:
      VUE_APP_BASE_URL: http://172.26.136.11:8080
    ports:
      - 8081:80
    restart: always