---
# install require dependencies on instances
- hosts: all
  vars_files:
    - vars/git_credentials.yml
  vars:
    remote_user: ubuntu
  gather_facts: true
  roles:
    # - role: openstack-mount-vol
    - role: openstack-config